package modelo.entidad;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Recibe generated by hbm2java
 */
@Entity
@Table(name="recibe" ,catalog="escuela")
public class Recibe  implements java.io.Serializable {
     private String cursoEscolar;
     private Alumno alumno;
     private Asignatura asignatura;

    public Recibe() {
    }

    public Recibe(String cursoEscolar, Alumno alumno, Asignatura asignatura) {
       this.cursoEscolar = cursoEscolar;
       this.alumno = alumno;
       this.asignatura = asignatura;
    }
   
     @Id 

    
    @Column(name="CursoEscolar", unique=true, nullable=false, length=50)
    public String getCursoEscolar() {
        return this.cursoEscolar;
    }
    
    public void setCursoEscolar(String cursoEscolar) {
        this.cursoEscolar = cursoEscolar;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NumMatricula", nullable=false)
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CodAsignatura", nullable=false)
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }




}


